##路径
domain: 127.0.0.1
domain_base: http://127.0.0.1:3000

domain_image: http://127.0.0.1:3000/asset

#新闻最终页
news_url: http://127.0.0.1:3000/post/news/%s/%s
#作品最终页
arts_url: http://127.0.0.1:3000/teach/%s/%s
#书籍最终页
books_url: http://127.0.0.1:3000/book/%s/%s

#设置图片支持的格式
verify_img_type: ["jpg","jpeg","pjpeg","png","x-png","gif"]
