##路径
domain: muc.shijue.me
domain_base: http://muc.shijue.me

domain_image: http://muc.shijue.me/asset

#新闻最终页
news_url: http://muc.shijue.me/news/%s/%s
#作品最终页
arts_url: http://muc.shijue.me/teach/%s/%s
#书籍最终页
books_url: http://muc.shijue.me/book/%s/%s


#设置图片支持的格式
verify_img_type: ["JPG","JPEG","PJPEG","PNG","X-PNG","GIF"]
