##路径
domain: http://muc.shijue.me
domain_base: http://muc.shijue.me

domain_image: http://muc.shijue.me/asset

#新闻最终页
news_url: http://muc.shijue.me/post/%s/%s
#作品最终页
arts_url: http://muc.shijue.me/art/%s/%s
#书籍最终页
books_url: http://muc.shijue.me/book/%s/%s
# 师资最终页
teachers_url: http://muc.shijue.me/teacher/%s/%s
# 通用
commons_url: http://muc.shijue.me/%s/%s/%s


#设置图片支持的格式
verify_img_type: ["JPG","JPEG","PJPEG","PNG","X-PNG","GIF"]

#作品图规格
image_art_format:
  max_size: 5
  min_w_h: [170,120]
  b: 740
  m: [170,120]
  s: [50,50]

#编辑器图规格
image_editor_format:
  max_size: 2
  min_w_h: [50,50]
  b: 740
  m: [170,120]
  s: [50,50]

#头像规格
image_avatar_format:
  max_size: 5
  min_w_h: [180, 180]
  o: 180
  b: 180x180
  m: 100x100
  s: 50x50
